### PR TITLE
SSSSCryptoCallbacks.getSecretStorageKey: Test if delegateCryptoCallbacks has getSecretStorageKey

### LINKED ISSUE #1845: SSSSCryptoCallbacks: this.delegateCryptoCallbacks.getSecretStorageKey is not a function
**Describe the bug**
`delegateCryptoCallbacks.getSecretStorageKey` is used without a check of whether it is defined.

https://github.com/matrix-org/matrix-js-sdk/blob/a69d9a9f20b680e3710e0f43cca68a2ce31ba030/src/crypto/EncryptionSetup.ts#L369-L370

**To Reproduce**
1. Call `createClient` with `cryptoCallbacks: undefined` or `cryptoCallbacks: {}` (both are valid and don't have a `getSecretStorageKey` property)

**Expected behavior**
It either works or a proper error is thrown.

** Additional notes**
`ICryptoCallbacks.getSecretStorageKey` is declared optional.
https://github.com/matrix-org/matrix-js-sdk/blob/b63de6a902a9e1f8ffd7697dea33820fc04f028e/src/matrix.ts#L109

### PR DESCRIPTION
**Pull request by jaller94**
Fixes #1845 

Notes: Fix a JavaScript error on matrixClient.bootstrapSecretStorage() if matrixClient.cryptoCallbacks.getSecretStorageKey is not defined.

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

File: src/crypto/EncryptionSetup.ts [hunk 1]
```diff
@@ -365,7 +365,7 @@ class SSSSCryptoCallbacks {
         }
         // if we don't have the key cached yet, ask
         // for it to the general crypto callbacks and cache it
-        if (this.delegateCryptoCallbacks) {
+        if (this.delegateCryptoCallbacks && this.delegateCryptoCallbacks.getSecretStorageKey) {
```
Comment (Palid) [inline src/crypto/EncryptionSetup.ts:368]:
```suggestion
        if (this?.delegateCryptoCallbacks?.getSecretStorageKey) {
```
Makes it slightly easier for the eyes. :)

Comment (jaller94) [reply src/crypto/EncryptionSetup.ts:368]: No need to check `this`.
```suggestion
        if (this.delegateCryptoCallbacks?.getSecretStorageKey) {
```

File: src/crypto/EncryptionSetup.ts [hunk 2]
```diff
@@ -365,7 +365,7 @@ class SSSSCryptoCallbacks {
         }
         // if we don't have the key cached yet, ask
         // for it to the general crypto callbacks and cache it
-        if (this.delegateCryptoCallbacks) {
+        if (this.delegateCryptoCallbacks?.getSecretStorageKey) {
```
Comment (Palid) [inline src/crypto/EncryptionSetup.ts:368]: can `delegateCryptoCallbacks` fail? If yes we need to make `this?.delegateCryptoCallbacks?.getSecretStorageKey` instead to check for both cases.

File: src/crypto/EncryptionSetup.ts (hunk 1 above)
Comment (Palid) [reply src/crypto/EncryptionSetup.ts]: @jaller94 Could you change it in line 381 too, so the behavior's the same in both if we don't need to check for `this`? It seems that it'll always be defined, but may be an empty object sometimes.

File: src/crypto/EncryptionSetup.ts (hunk 2 above)
Comment (jaller94) [reply src/crypto/EncryptionSetup.ts:368]: As long as `this` is truthy, it won't throw.

Comment (jaller94) [inline src/crypto/EncryptionSetup.ts:368]: According to the constructor, we shouldn't need this `?` as `delegateCryptoCallbacks` must be a `ICryptoCallbacks`.

There's another issue that
* either the constructor's signature of `SSSSCryptoCallbacks` and `EncryptionSetupBuilder` should allow `ICryptoCallbacks|undefined` or
* [`MatrixClient.cryptoCallbacks`](https://github.com/matrix-org/matrix-js-sdk/blob/a69d9a9f20b680e3710e0f43cca68a2ce31ba030/src/client.ts#L315) must not be undefined.

It's handed over here.
https://github.com/matrix-org/matrix-js-sdk/blob/a69d9a9f20b680e3710e0f43cca68a2ce31ba030/src/crypto/index.ts#L616-L620

Comment (jaller94) [reply src/crypto/EncryptionSetup.ts:368]: https://github.com/matrix-org/matrix-js-sdk/pull/1847/files#diff-2ed9f095536152a0f96b01826f2bc6fa8d04591b7c5bc02782804d4e12bdbc31R382

regards `this.delegateCryptoCallbacks` as optional, so I guess version 1 is/was supposed to be the truth.

Comment (jaller94) [reply src/crypto/EncryptionSetup.ts:368]: As that's yet a different issue, I solved that in a separate PR: #1849

File: src/crypto/EncryptionSetup.ts (hunk 1 above)
Comment (jaller94) [reply src/crypto/EncryptionSetup.ts]: If #1849 gets accepted, `delegateCryptoCallbacks` becomes optional and we should keep them like this.

File: src/crypto/EncryptionSetup.ts (hunk 2 above)
Comment (Palid) [reply src/crypto/EncryptionSetup.ts:368]: @jaller94 so let's go back to checking `this?.delegateCryptoCallbacks?.getSecretStorageKey`. You can just click commit suggestion. 😄

Comment (jaller94) [reply src/crypto/EncryptionSetup.ts:368]: I don't agree. According to our types, `this` and `this.delegateCryptoCallbacks` are safe.
However, it doesn't hurt to add the question marks.

```suggestion
        if (this?.delegateCryptoCallbacks?.getSecretStorageKey) {
```

**Comment by jaller94** [comment]
@Palid Could you have another look at this?

**Review by Palid — APPROVED** [review]

**Comment by Palid** [comment]
> @Palid Could you have another look at this?

LGTM. Sorry!
