### PR TITLE
Don't crash with undefined room in `processBeaconEvents()`

### LINKED ISSUE #2494: Crash on processBeaconEvents due to null room in notificationTimeline
**Describe the bug**
When loading the client timeline set data, `processBeaconEvents` is called on the matrix events for the notification timeline. However, notification timeline has no room associated with it.

The `processBeaconEvents` function expects a room if there are any matrix events.

Here is the callback on the sync event:
image

And the call to processBeaconEvents:
image

**To Reproduce**
Create / start the client
Create a notification timelineset
Request timeline notifications

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103

This is not an issue in version 16 of the SDK. It is present in 17, 18, and 19.

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2494

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Don't crash with undefined room in `processBeaconEvents()` ([\#2500](https://github.com/matrix-org/matrix-js-sdk/pull/2500)). Fixes #2494.

### CODE REVIEW

File: src/client.ts [hunk 1]
```diff
@@ -8947,9 +8947,9 @@ export class MatrixClient extends TypedEventEmitter<EmittedEvents, ClientEventHa
         room: Room,
         events?: MatrixEvent[],
     ): void {
-        if (!events?.length) {
-            return;
-        }
+        if (!events?.length) return;
+        if (!room) return;
```
Comment (t3chguy) [inline src/client.ts:8951]: L8947 says room must be provided

Comment (SimonBrandner) [reply src/client.ts:8951]: Well, it feels safer to have the if statement inside the method in case something like this happens again though it feels weird to say the room can be falsey, so I am not sure which one I should go with...

**Review by t3chguy — APPROVED** [review]
